server:
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}
  port: ${SERVER_PORT}
  ssl:
    key-store: classpath:keystore/usociety.p12
    key-store-password: qwerty
    keyStoreType: PKCS12
    keyAlias: usociety
    enabled: true

spring:
  profiles:
    active: ${SERVER_ACTIVE_PROFILE}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

security:
  oauth2:
    resource.filter-order: 3
config:
  table: ${SERVER_CONFIG_TABLE_NAME}

---
spring:
  profiles: dev, prod
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${PROJECT_DATABASE_PORT}/${PROJECT_DATABASE_NAME}?zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=${SERVER_TIME_ZONE}
    username: ${PROJECT_DATABASE_USER}
    password: ${PROJECT_DATABASE_PASSWORD}
    platform: mysql
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
config:
  timezone: ${SERVER_TIME_ZONE}


---
spring:
  profiles: dev
  logging:
    level:
      root: TRACE
      org.springframework.web: TRACE
      org.springframework.web-security: TRACE
      org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
      reactor.ipc.netty:
        channel.ContextHandler: debug
        reactor.ipc.netty.http.client.HttpClient: debug